### PR TITLE
Use config argument on parse! to set config

### PR DESCRIPTION
**Pull request by duleorlovic**
When I use scraper from ruby code, I need to set config dynamically (for each run I need to set cookies so I do not need to login again).
This pull requests allows me to overwrite config

### CODE REVIEW

**Comment by jkeen** [comment]
I like this, and I'd love to see this done on `crawl!` too.

I need to pass in login credentials for my spider to use, and currently I have to do some hokey ruby metaprogramming to pass in config or data at the top level, and it's silly.

**Comment by jkeen** [comment]
Oh looks like another fork was made with that option: https://github.com/dtengeri/kimuraframework

@dtengeri you planning on submitting a PR?

**Comment by vifreefly** [comment]
@duleorlovic Thanks, merged

**Comment by amitpatelx** [comment]
We have thousands of spiders and so many are blocked later after crawling a couple of times. We have been managing configuration via UI. So enabling proxy is also one of the configurations we need frequently.

We use `open_spider` callback to modify the config dynamically.

**Pull request merged**
